# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 01:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_id', models.CharField(max_length=4, unique=True)),
                ('research_person', models.CharField(max_length=100)),
                ('added', models.DateTimeField(auto_now=True)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Drink')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='drinksurvey',
            name='research_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Location'),
        ),
        migrations.AddField(
            model_name='drinksurvey',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
